package lentopallotilastotyokalu.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import lentopallotilastotyokalu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.11 19:01:42 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JoukkueetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa32 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa32() throws SailoException {    // Joukkueet: 32
    Joukkueet joukkueet = new Joukkueet(); 
    Joukkue tiimi1 = new Joukkue(), tiimi2 = new Joukkue(); 
    assertEquals("From: Joukkueet line: 36", 0, joukkueet.getLkm()); 
    joukkueet.lisaa(tiimi1); assertEquals("From: Joukkueet line: 37", 1, joukkueet.getLkm()); 
    joukkueet.lisaa(tiimi2); assertEquals("From: Joukkueet line: 38", 2, joukkueet.getLkm()); 
    joukkueet.lisaa(tiimi1); assertEquals("From: Joukkueet line: 39", 3, joukkueet.getLkm()); 
    assertEquals("From: Joukkueet line: 40", tiimi1, joukkueet.anna(0)); 
    assertEquals("From: Joukkueet line: 41", tiimi2, joukkueet.anna(1)); 
    assertEquals("From: Joukkueet line: 42", tiimi1, joukkueet.anna(2)); 
    assertEquals("From: Joukkueet line: 43", false, joukkueet.anna(1) == tiimi1); 
    assertEquals("From: Joukkueet line: 44", true, joukkueet.anna(1) == tiimi2); 
    try {
    assertEquals("From: Joukkueet line: 45", tiimi1, joukkueet.anna(3)); 
    fail("Joukkueet: 45 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    joukkueet.lisaa(tiimi1); assertEquals("From: Joukkueet line: 46", 4, joukkueet.getLkm()); 
    joukkueet.lisaa(tiimi1); assertEquals("From: Joukkueet line: 47", 5, joukkueet.getLkm()); 
    joukkueet.lisaa(tiimi1); assertEquals("From: Joukkueet line: 48", 6, joukkueet.getLkm()); 
    joukkueet.lisaa(tiimi1); assertEquals("From: Joukkueet line: 49", 7, joukkueet.getLkm()); 
    joukkueet.lisaa(tiimi1); assertEquals("From: Joukkueet line: 50", 8, joukkueet.getLkm()); 
    joukkueet.lisaa(tiimi1); assertEquals("From: Joukkueet line: 51", 9, joukkueet.getLkm()); 
    joukkueet.lisaa(tiimi1); assertEquals("From: Joukkueet line: 52", 10, joukkueet.getLkm()); 
  } // Generated by ComTest END
}