package lentopallotilastotyokalu.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import lentopallotilastotyokalu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.23 08:30:14 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JoukkueTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi40 */
  @Test
  public void testRekisteroi40() {    // Joukkue: 40
    Joukkue tiimi1 = new Joukkue(); 
    assertEquals("From: Joukkue line: 42", 0, tiimi1.getTunnusNro()); 
    tiimi1.rekisteroi(); 
    Joukkue tiimi2 = new Joukkue(); 
    tiimi2.rekisteroi(); 
    int n1 = tiimi1.getTunnusNro(); 
    int n2 = tiimi2.getTunnusNro(); 
    assertEquals("From: Joukkue line: 48", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi68 */
  @Test
  public void testGetNimi68() {    // Joukkue: 68
    Joukkue tiimi = new Joukkue(); 
    tiimi.taytaPuulaakiTiedoilla(); 
    { String _l_=tiimi.getNimi(),_r_="Puulaaki .*"; if ( !_l_.matches(_r_) ) fail("From: Joukkue line: 71" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END
}