package lentopallotilastotyokalu.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import lentopallotilastotyokalu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.20 09:47:56 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JoukkueTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi64 */
  @Test
  public void testRekisteroi64() {    // Joukkue: 64
    Joukkue tiimi1 = new Joukkue(); 
    assertEquals("From: Joukkue line: 66", 0, tiimi1.getTunnusNro()); 
    tiimi1.rekisteroi(); 
    Joukkue tiimi2 = new Joukkue(); 
    tiimi2.rekisteroi(); 
    int n1 = tiimi1.getTunnusNro(); 
    int n2 = tiimi2.getTunnusNro(); 
    assertEquals("From: Joukkue line: 72", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString105 */
  @Test
  public void testToString105() {    // Joukkue: 105
    Joukkue joukkue = new Joukkue(); 
    Joukkue joukkue2 = new Joukkue("Joukkue|viivalla"); 
    joukkue.parse("   8  |  Oulun Etta  |"); 
    assertEquals("From: Joukkue line: 109", "8|Oulun Etta|", joukkue.toString()); 
    assertEquals("From: Joukkue line: 110", "0|Joukkue\\|viivalla|", joukkue2.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse129 */
  @Test
  public void testParse129() {    // Joukkue: 129
    Joukkue joukkue = new Joukkue(); 
    joukkue.parse("   8  |  Oulun Etta  |"); 
    assertEquals("From: Joukkue line: 132", "8|Oulun Etta|", joukkue.toString()); 
    Joukkue joukkue2 = new Joukkue(); 
    joukkue2.parse("   8  |Joukkue\\|viivalla|"); 
    assertEquals("From: Joukkue line: 136", "Joukkue|viivalla", joukkue2.getNimi()); 
    joukkue.rekisteroi(); 
    int n = joukkue.getTunnusNro(); 
    joukkue.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    joukkue.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Joukkue line: 142", n+20+1, joukkue.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi159 */
  @Test
  public void testGetNimi159() {    // Joukkue: 159
    Joukkue tiimi = new Joukkue(); 
    tiimi.taytaPuulaakiTiedoilla(); 
    { String _l_=tiimi.getNimi(),_r_="Puulaaki .*"; if ( !_l_.matches(_r_) ) fail("From: Joukkue line: 162" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END
}