package lentopallotilastotyokalu.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import lentopallotilastotyokalu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.20 10:51:17 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelaajaTest {



  // Generated by ComTest BEGIN
  /** testAseta53 */
  @Test
  public void testAseta53() {    // Pelaaja: 53
    Pelaaja pelaaja = new Pelaaja(); 
    assertEquals("From: Pelaaja line: 55", null, pelaaja.aseta(3,"Ankka Aku")); 
    assertEquals("From: Pelaaja line: 56", null, pelaaja.aseta(1,"5")); 
    assertEquals("From: Pelaaja line: 57", null, pelaaja.aseta(4,"passari")); 
    assertEquals("From: Pelaaja line: 58", null, pelaaja.aseta(2,"58")); 
    assertEquals("From: Pelaaja line: 59", "5", pelaaja.getKentta(1)); 
    assertEquals("From: Pelaaja line: 60", "Ankka Aku", pelaaja.getKentta(3)); 
    assertEquals("From: Pelaaja line: 61", "passari", pelaaja.getKentta(4)); 
    assertEquals("From: Pelaaja line: 62", "58", pelaaja.getKentta(2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi170 */
  @Test
  public void testRekisteroi170() {    // Pelaaja: 170
    Pelaaja peluri1 = new Pelaaja(); 
    assertEquals("From: Pelaaja line: 172", 0, peluri1.getTunnusNro()); 
    peluri1.rekisteroi(); 
    Pelaaja peluri2 = new Pelaaja(); 
    peluri2.rekisteroi(); 
    int n1 = peluri1.getTunnusNro(); 
    int n2 = peluri2.getTunnusNro(); 
    assertEquals("From: Pelaaja line: 178", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi245 */
  @Test
  public void testGetNimi245() {    // Pelaaja: 245
    Pelaaja pete = new Pelaaja(); 
    pete.taytaEsimerkkiTiedoilla(); 
    { String _l_=pete.getNimi(),_r_="Pete Pelaaja .*"; if ( !_l_.matches(_r_) ) fail("From: Pelaaja line: 248" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse296 */
  @Test
  public void testParse296() {    // Pelaaja: 296
    Pelaaja pelaaja = new Pelaaja(); 
    pelaaja.parse("1   |1     |2          |Eemil Tervaportti |Passari        | "); 
    assertEquals("From: Pelaaja line: 299", "1|1|2|Eemil Tervaportti|Passari|", pelaaja.toString()); 
    Pelaaja pelaaja2 = new Pelaaja(); 
    pelaaja2.parse("1   |1     |2          |Eemil\\|Tervaportti |Passari        | "); 
    assertEquals("From: Pelaaja line: 303", "Eemil|Tervaportti", pelaaja2.getKentta(3)); 
    assertEquals("From: Pelaaja line: 304", "1|1|2|Eemil\\|Tervaportti|Passari|", pelaaja2.toString()); 
    Pelaaja pelaaja3 = new Pelaaja(); 
    pelaaja3.parse("1   |1     |2          |Eemil\\|Tervaportti |Pass\\|ari        | "); 
    assertEquals("From: Pelaaja line: 308", "Eemil|Tervaportti", pelaaja3.getKentta(3)); 
    assertEquals("From: Pelaaja line: 309", "Pass|ari", pelaaja3.getKentta(4)); 
    assertEquals("From: Pelaaja line: 310", "1|1|2|Eemil\\|Tervaportti|Pass\\|ari|", pelaaja3.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString329 */
  @Test
  public void testToString329() {    // Pelaaja: 329
    Pelaaja pelaaja = new Pelaaja(); 
    pelaaja.parse("1   |1     |2          |Eemil Tervaportti |Passari        | "); 
    assertEquals("From: Pelaaja line: 332", "1|1|2|Eemil Tervaportti|Passari|", pelaaja.toString()); 
    Pelaaja pelaaja2 = new Pelaaja(); 
    pelaaja2.aseta(3, "nimi|viivalla"); pelaaja2.aseta(4, "pelipaikka|viivalla"); 
    assertEquals("From: Pelaaja line: 336", "0|0|0|nimi\\|viivalla|pelipaikka\\|viivalla|", pelaaja2.toString()); 
    Pelaaja pelaaja3 = new Pelaaja(); 
    pelaaja3.aseta(3, "nimi|viivalla"); ; 
    assertEquals("From: Pelaaja line: 340", "0|0|0|nimi\\|viivalla||", pelaaja3.toString()); 
    Pelaaja pelaaja4 = new Pelaaja(); 
    pelaaja4.aseta(4, "pelipaikka|viivalla"); 
    assertEquals("From: Pelaaja line: 344", "0|0|0||pelipaikka\\|viivalla|", pelaaja4.toString()); 
  } // Generated by ComTest END
}