package lentopallotilastotyokalu.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import lentopallotilastotyokalu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.30 12:09:05 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelaajaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi56 */
  @Test
  public void testRekisteroi56() {    // Pelaaja: 56
    Pelaaja peluri1 = new Pelaaja(); 
    assertEquals("From: Pelaaja line: 58", 0, peluri1.getTunnusNro()); 
    peluri1.rekisteroi(); 
    Pelaaja peluri2 = new Pelaaja(); 
    peluri2.rekisteroi(); 
    int n1 = peluri1.getTunnusNro(); 
    int n2 = peluri2.getTunnusNro(); 
    assertEquals("From: Pelaaja line: 64", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi114 */
  @Test
  public void testGetNimi114() {    // Pelaaja: 114
    Pelaaja pete = new Pelaaja(); 
    pete.taytaEsimerkkiTiedoilla(); 
    { String _l_=pete.getNimi(),_r_="Pete Pelaaja .*"; if ( !_l_.matches(_r_) ) fail("From: Pelaaja line: 117" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse138 */
  @Test
  public void testParse138() {    // Pelaaja: 138
    Pelaaja pelaaja = new Pelaaja(); 
    pelaaja.parse("1   |1     |2          |Eemil Tervaportti |Passari        | "); 
    assertEquals("From: Pelaaja line: 141", "1|1|2|Eemil Tervaportti|Passari|", pelaaja.toString()); 
    pelaaja.rekisteroi(); 
    int n = pelaaja.getTunnusNro(); 
    pelaaja.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    pelaaja.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Pelaaja line: 147", n+20+1, pelaaja.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString163 */
  @Test
  public void testToString163() {    // Pelaaja: 163
    Pelaaja pelaaja = new Pelaaja(); 
    pelaaja.parse("1   |1     |2          |Eemil Tervaportti |Passari        | "); 
    assertEquals("From: Pelaaja line: 166", "1|1|2|Eemil Tervaportti|Passari|", pelaaja.toString()); 
  } // Generated by ComTest END
}