package lentopallotilastotyokalu.test;
// Generated by ComTest BEGIN
import java.io.File;
import lentopallotilastotyokalu.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.19 10:55:12 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelaajatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa51 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa51() throws SailoException {    // Pelaajat: 51
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja pelimies1 = new Pelaaja(), pelimies2 = new Pelaaja(); 
    assertEquals("From: Pelaajat line: 55", 0, pelaajat.getLkm()); 
    pelaajat.lisaa(pelimies1); assertEquals("From: Pelaajat line: 56", 1, pelaajat.getLkm()); 
    pelaajat.lisaa(pelimies2); assertEquals("From: Pelaajat line: 57", 2, pelaajat.getLkm()); 
    pelaajat.lisaa(pelimies1); assertEquals("From: Pelaajat line: 58", 3, pelaajat.getLkm()); 
    assertEquals("From: Pelaajat line: 59", pelimies1, pelaajat.anna(0)); 
    assertEquals("From: Pelaajat line: 60", pelimies2, pelaajat.anna(1)); 
    assertEquals("From: Pelaajat line: 61", pelimies1, pelaajat.anna(2)); 
    assertEquals("From: Pelaajat line: 62", false, pelaajat.anna(1) == pelimies1); 
    assertEquals("From: Pelaajat line: 63", true, pelaajat.anna(1) == pelimies2); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista79 
   * @throws SailoException when error
   */
  @Test
  public void testPoista79() throws SailoException {    // Pelaajat: 79
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja peluri1 = new Pelaaja(), peluri2 = new Pelaaja(), peluri3 = new Pelaaja(); 
    peluri1.rekisteroi(); peluri2.rekisteroi(); peluri3.rekisteroi(); 
    int id1 = peluri1.getTunnusNro(); 
    pelaajat.lisaa(peluri1); pelaajat.lisaa(peluri2); pelaajat.lisaa(peluri3); 
    assertEquals("From: Pelaajat line: 86", 1, pelaajat.poista(id1+1)); 
    assertEquals("From: Pelaajat line: 87", null, pelaajat.annaId(id1+1)); assertEquals("From: Pelaajat line: 87", 2, pelaajat.getLkm()); 
    assertEquals("From: Pelaajat line: 88", 1, pelaajat.poista(id1)); assertEquals("From: Pelaajat line: 88", 1, pelaajat.getLkm()); 
    assertEquals("From: Pelaajat line: 89", 0, pelaajat.poista(id1+3)); assertEquals("From: Pelaajat line: 89", 1, pelaajat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsiId122 
   * @throws SailoException when error
   */
  @Test
  public void testEtsiId122() throws SailoException {    // Pelaajat: 122
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja peluri1 = new Pelaaja(), peluri2 = new Pelaaja(), peluri3 = new Pelaaja(); 
    peluri1.rekisteroi(); peluri2.rekisteroi(); peluri3.rekisteroi(); 
    int id1 = peluri1.getTunnusNro(); 
    pelaajat.lisaa(peluri1); pelaajat.lisaa(peluri2); pelaajat.lisaa(peluri3); 
    assertEquals("From: Pelaajat line: 129", 1, pelaajat.etsiId(id1+1)); 
    assertEquals("From: Pelaajat line: 130", 2, pelaajat.etsiId(id1+2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta175 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta175() throws SailoException {    // Pelaajat: 175
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja pelaaja1 = new Pelaaja(), pelaaja2 = new Pelaaja(); 
    pelaaja1.rekisteroi(); 
    pelaaja2.rekisteroi(); 
    pelaaja1.taytaEsimerkkiTiedoilla(); 
    pelaaja2.taytaEsimerkkiTiedoilla(); 
    String testiTiedosto = "testipelaajat"; 
    File ftied = new File(testiTiedosto+".dat"); 
    ftied.delete(); 
    try {
    pelaajat.lueTiedostosta(testiTiedosto); 
    fail("Pelaajat: 188 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    pelaajat.lisaa(pelaaja1); 
    pelaajat.lisaa(pelaaja2); 
    pelaajat.tallenna(); 
    pelaajat = new Pelaajat();  // Poistetaan vanhat luomalla uusi
    pelaajat.lueTiedostosta(testiTiedosto);  // johon ladataan tiedot tiedostosta.
    Iterator<Pelaaja> i = pelaajat.iterator(); 
    assertEquals("From: Pelaajat line: 195", pelaaja1.toString(), i.next().toString()); 
    assertEquals("From: Pelaajat line: 196", pelaaja2.toString(), i.next().toString()); 
    assertEquals("From: Pelaajat line: 197", false, i.hasNext()); 
    pelaajat.lisaa(pelaaja2); 
    pelaajat.tallenna(); 
    assertEquals("From: Pelaajat line: 200", true, ftied.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi281 
   * @throws SailoException when error
   */
  @Test
  public void testEtsi281() throws SailoException {    // Pelaajat: 281
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja pelaaja1 = new Pelaaja(), pelaaja2 = new Pelaaja(); 
    pelaaja1.parse("1   |1     |2          |Eemil Tervaportti |Passari        | "); 
    pelaaja2.parse("5   |2     |26         |Pete Pelaaja      |Hakkuri        | "); 
    pelaajat.lisaa(pelaaja1); pelaajat.lisaa(pelaaja2); 
    List<Pelaaja> loytyneet; 
    loytyneet = (List<Pelaaja>)pelaajat.etsi("*s*",4); 
    assertEquals("From: Pelaajat line: 290", 1, loytyneet.size()); 
    assertEquals("From: Pelaajat line: 291", true, loytyneet.get(0) == pelaaja1); 
    loytyneet = (List<Pelaaja>)pelaajat.etsi("*2*",2); 
    assertEquals("From: Pelaajat line: 294", 2, loytyneet.size()); 
    assertEquals("From: Pelaajat line: 295", true, loytyneet.get(0) == pelaaja1); 
    assertEquals("From: Pelaajat line: 296", true, loytyneet.get(1) == pelaaja2); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPelaajatIterator316 
   * @throws SailoException when error
   */
  @Test
  public void testPelaajatIterator316() throws SailoException {    // Pelaajat: 316
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja pelaaja1 = new Pelaaja(), pelaaja2 = new Pelaaja(); 
    pelaaja1.rekisteroi(); pelaaja2.rekisteroi(); 
    pelaajat.lisaa(pelaaja1); 
    pelaajat.lisaa(pelaaja2); 
    pelaajat.lisaa(pelaaja1); 
    StringBuffer ids = new StringBuffer(30); 
    for (Pelaaja pelaaja:pelaajat) // Kokeillaan for-silmukan toimintaa
    ids.append(" "+pelaaja.getTunnusNro()); 
    String tulos = " " + pelaaja1.getTunnusNro() + " " + pelaaja2.getTunnusNro() + " " + pelaaja1.getTunnusNro(); 
    assertEquals("From: Pelaajat line: 335", tulos, ids.toString()); 
    ids = new StringBuffer(30); 
    for (Iterator<Pelaaja>  i=pelaajat.iterator(); i.hasNext(); ) { // ja iteraattorin toimintaa
    Pelaaja pelaaja = i.next(); 
    ids.append(" "+pelaaja.getTunnusNro()); 
    }
    assertEquals("From: Pelaajat line: 343", tulos, ids.toString()); 
    Iterator<Pelaaja>  i=pelaajat.iterator(); 
    assertEquals("From: Pelaajat line: 346", true, i.next() == pelaaja1); 
    assertEquals("From: Pelaajat line: 347", true, i.next() == pelaaja2); 
    assertEquals("From: Pelaajat line: 348", true, i.next() == pelaaja1); 
    try {
    i.next(); 
    fail("Pelaajat: 350 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}