package lentopallotilastotyokalu.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import lentopallotilastotyokalu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.11 19:08:02 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelaajaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi55 */
  @Test
  public void testRekisteroi55() {    // Pelaaja: 55
    Pelaaja peluri1 = new Pelaaja(); 
    assertEquals("From: Pelaaja line: 57", 0, peluri1.getTunnusNro()); 
    peluri1.rekisteroi(); 
    Pelaaja peluri2 = new Pelaaja(); 
    peluri2.rekisteroi(); 
    int n1 = peluri1.getTunnusNro(); 
    int n2 = peluri2.getTunnusNro(); 
    assertEquals("From: Pelaaja line: 63", n2-1, n1); 
    assertEquals("From: Pelaaja line: 64", 1, peluri1.getpId()); 
    assertEquals("From: Pelaaja line: 65", 2, peluri2.getpId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi110 */
  @Test
  public void testGetNimi110() {    // Pelaaja: 110
    Pelaaja pete = new Pelaaja(); 
    pete.taytaEsimerkkiTiedoilla(); 
    { String _l_=pete.getNimi(),_r_="Pete Pelaaja .*"; if ( !_l_.matches(_r_) ) fail("From: Pelaaja line: 113" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END
}