package lentopallotilastotyokalu.test;
// Generated by ComTest BEGIN
import java.io.File;
import lentopallotilastotyokalu.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.06 07:43:56 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelaajatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa45 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa45() throws SailoException {    // Pelaajat: 45
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja pelimies1 = new Pelaaja(), pelimies2 = new Pelaaja(); 
    assertEquals("From: Pelaajat line: 49", 0, pelaajat.getLkm()); 
    pelaajat.lisaa(pelimies1); assertEquals("From: Pelaajat line: 50", 1, pelaajat.getLkm()); 
    pelaajat.lisaa(pelimies2); assertEquals("From: Pelaajat line: 51", 2, pelaajat.getLkm()); 
    pelaajat.lisaa(pelimies1); assertEquals("From: Pelaajat line: 52", 3, pelaajat.getLkm()); 
    assertEquals("From: Pelaajat line: 53", pelimies1, pelaajat.anna(0)); 
    assertEquals("From: Pelaajat line: 54", pelimies2, pelaajat.anna(1)); 
    assertEquals("From: Pelaajat line: 55", pelimies1, pelaajat.anna(2)); 
    assertEquals("From: Pelaajat line: 56", false, pelaajat.anna(1) == pelimies1); 
    assertEquals("From: Pelaajat line: 57", true, pelaajat.anna(1) == pelimies2); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta94 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta94() throws SailoException {    // Pelaajat: 94
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja pelaaja1 = new Pelaaja(), pelaaja2 = new Pelaaja(); 
    pelaaja1.rekisteroi(); 
    pelaaja2.rekisteroi(); 
    pelaaja1.taytaEsimerkkiTiedoilla(); 
    pelaaja2.taytaEsimerkkiTiedoilla(); 
    String testiTiedosto = "testipelaajat"; 
    File ftied = new File(testiTiedosto+".dat"); 
    ftied.delete(); 
    try {
    pelaajat.lueTiedostosta(testiTiedosto); 
    fail("Pelaajat: 107 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    pelaajat.lisaa(pelaaja1); 
    pelaajat.lisaa(pelaaja2); 
    pelaajat.tallenna(); 
    pelaajat = new Pelaajat();  // Poistetaan vanhat luomalla uusi
    pelaajat.lueTiedostosta(testiTiedosto);  // johon ladataan tiedot tiedostosta.
    Iterator<Pelaaja> i = pelaajat.iterator(); 
    assertEquals("From: Pelaajat line: 114", pelaaja1.toString(), i.next().toString()); 
    assertEquals("From: Pelaajat line: 115", pelaaja2.toString(), i.next().toString()); 
    assertEquals("From: Pelaajat line: 116", false, i.hasNext()); 
    pelaajat.lisaa(pelaaja2); 
    pelaajat.tallenna(); 
    assertEquals("From: Pelaajat line: 119", true, ftied.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPelaajatIterator197 
   * @throws SailoException when error
   */
  @Test
  public void testPelaajatIterator197() throws SailoException {    // Pelaajat: 197
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja pelaaja1 = new Pelaaja(), pelaaja2 = new Pelaaja(); 
    pelaaja1.rekisteroi(); pelaaja2.rekisteroi(); 
    pelaajat.lisaa(pelaaja1); 
    pelaajat.lisaa(pelaaja2); 
    pelaajat.lisaa(pelaaja1); 
    StringBuffer ids = new StringBuffer(30); 
    for (Pelaaja pelaaja:pelaajat) // Kokeillaan for-silmukan toimintaa
    ids.append(" "+pelaaja.getTunnusNro()); 
    String tulos = " " + pelaaja1.getTunnusNro() + " " + pelaaja2.getTunnusNro() + " " + pelaaja1.getTunnusNro(); 
    assertEquals("From: Pelaajat line: 216", tulos, ids.toString()); 
    ids = new StringBuffer(30); 
    for (Iterator<Pelaaja>  i=pelaajat.iterator(); i.hasNext(); ) { // ja iteraattorin toimintaa
    Pelaaja pelaaja = i.next(); 
    ids.append(" "+pelaaja.getTunnusNro()); 
    }
    assertEquals("From: Pelaajat line: 224", tulos, ids.toString()); 
    Iterator<Pelaaja>  i=pelaajat.iterator(); 
    assertEquals("From: Pelaajat line: 227", true, i.next() == pelaaja1); 
    assertEquals("From: Pelaajat line: 228", true, i.next() == pelaaja2); 
    assertEquals("From: Pelaajat line: 229", true, i.next() == pelaaja1); 
    try {
    i.next(); 
    fail("Pelaajat: 231 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}