package lentopallotilastotyokalu.test;
// Generated by ComTest BEGIN
import java.io.File;
import lentopallotilastotyokalu.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.19 09:40:29 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TilastotTest {



  // Generated by ComTest BEGIN
  /** testPoistaPelaajanTilastot50 */
  @Test
  public void testPoistaPelaajanTilastot50() {    // Tilastot: 50
    Tilastot tilastot = new Tilastot(); 
    Tilasto suorite21 = new Tilasto(); suorite21.taytaEsimerkkiTiedoilla(2); 
    Tilasto suorite11 = new Tilasto(); suorite11.taytaEsimerkkiTiedoilla(1); 
    Tilasto suorite22 = new Tilasto(); suorite22.taytaEsimerkkiTiedoilla(2); 
    Tilasto suorite12 = new Tilasto(); suorite12.taytaEsimerkkiTiedoilla(1); 
    Tilasto suorite23 = new Tilasto(); suorite23.taytaEsimerkkiTiedoilla(2); 
    tilastot.lisaa(suorite21); 
    tilastot.lisaa(suorite11); 
    tilastot.lisaa(suorite22); 
    tilastot.lisaa(suorite12); 
    tilastot.lisaa(suorite23); 
    assertEquals("From: Tilastot line: 62", 3, tilastot.poistaPelaajanTilastot(2)); assertEquals("From: Tilastot line: 62", 2, tilastot.getLkm()); 
    assertEquals("From: Tilastot line: 63", 0, tilastot.poistaPelaajanTilastot(3)); assertEquals("From: Tilastot line: 63", 2, tilastot.getLkm()); 
    List<Tilasto> h = tilastot.annaTilastot(2); 
    assertEquals("From: Tilastot line: 65", 0, h.size()); 
    h = tilastot.annaTilastot(1); 
    assertEquals("From: Tilastot line: 67", suorite11, h.get(0)); 
    assertEquals("From: Tilastot line: 68", suorite12, h.get(1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoistaViimeisin89 */
  @Test
  public void testPoistaViimeisin89() {    // Tilastot: 89
    Tilastot tilastot = new Tilastot(); 
    Tilasto tilasto1 = new Tilasto(), tilasto2 = new Tilasto(), tilasto3 = new Tilasto(); 
    tilasto1.taytaEsimerkkiTiedoilla(1); tilasto2.taytaEsimerkkiTiedoilla(1); tilasto3.taytaEsimerkkiTiedoilla(1); 
    tilastot.lisaa(tilasto1); tilastot.lisaa(tilasto2); tilastot.lisaa(tilasto3); 
    assertEquals("From: Tilastot line: 94", 3, tilastot.getLkm()); 
    tilastot.poistaViimeisin(); assertEquals("From: Tilastot line: 95", 2, tilastot.getLkm()); 
    tilastot.poistaViimeisin(); assertEquals("From: Tilastot line: 96", 1, tilastot.getLkm()); 
    tilastot.poistaViimeisin(); assertEquals("From: Tilastot line: 97", 0, tilastot.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoistaOttelunTilastot113 */
  @Test
  public void testPoistaOttelunTilastot113() {    // Tilastot: 113
    Tilastot tilastot = new Tilastot(); 
    Tilasto suorite1 = new Tilasto(1, "22.12.2121", "Puulaaki", "Ässä"); 
    Tilasto suorite2 = new Tilasto(3, "22.12.2121","VaLePa", "Piste"); 
    Tilasto suorite3 = new Tilasto(5, "23.12.2121","Puulaaki", "Piste"); 
    Tilasto suorite4 = new Tilasto(2, "23.12.2121","Puulaaki", "Piste"); 
    tilastot.lisaa(suorite1); tilastot.lisaa(suorite2); tilastot.lisaa(suorite3); tilastot.lisaa(suorite4); 
    assertEquals("From: Tilastot line: 120", 4, tilastot.getLkm()); 
    tilastot.poistaOttelunTilastot("22.12.2121", "Puulaaki"); assertEquals("From: Tilastot line: 121", 3, tilastot.getLkm()); 
    tilastot.poistaOttelunTilastot("22.12.2121", "VaLePa"); assertEquals("From: Tilastot line: 122", 2, tilastot.getLkm()); 
    tilastot.poistaOttelunTilastot("23.12.2121", "Puulaaki"); assertEquals("From: Tilastot line: 123", 0, tilastot.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta153 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta153() throws SailoException {    // Tilastot: 153
    Tilastot tilastot = new Tilastot(); 
    Tilasto tilasto1 = new Tilasto(), tilasto2 = new Tilasto(); 
    tilasto1.taytaEsimerkkiTiedoilla(5); 
    tilasto2.taytaEsimerkkiTiedoilla(5); 
    String testiTiedosto = "testitilastot"; 
    File ftied = new File(testiTiedosto+".dat"); 
    ftied.delete(); 
    try {
    tilastot.lueTiedostosta(testiTiedosto); 
    fail("Tilastot: 164 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    tilastot.lisaa(tilasto1); 
    tilastot.lisaa(tilasto2); 
    tilastot.tallenna(); 
    tilastot = new Tilastot();  // Poistetaan vanhat luomalla uusi
    tilastot.lueTiedostosta(testiTiedosto);  // johon ladataan tiedot tiedostosta.
    Iterator<Tilasto> i = tilastot.iterator(); 
    assertEquals("From: Tilastot line: 171", tilasto1.toString(), i.next().toString()); 
    assertEquals("From: Tilastot line: 172", tilasto2.toString(), i.next().toString()); 
    assertEquals("From: Tilastot line: 173", false, i.hasNext()); 
    tilastot.lisaa(tilasto2); 
    tilastot.tallenna(); 
    assertEquals("From: Tilastot line: 176", true, ftied.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator255 */
  @Test
  public void testIterator255() {    // Tilastot: 255
    Tilastot tilastoidut = new Tilastot(); 
    Tilasto tilasto21 = new Tilasto(2); tilastoidut.lisaa(tilasto21); 
    Tilasto tilasto11 = new Tilasto(1); tilastoidut.lisaa(tilasto11); 
    Tilasto tilasto22 = new Tilasto(2); tilastoidut.lisaa(tilasto22); 
    Tilasto tilasto12 = new Tilasto(1); tilastoidut.lisaa(tilasto12); 
    Tilasto tilasto23 = new Tilasto(2); tilastoidut.lisaa(tilasto23); 
    Iterator<Tilasto> i2=tilastoidut.iterator(); 
    assertEquals("From: Tilastot line: 267", tilasto21, i2.next()); 
    assertEquals("From: Tilastot line: 268", tilasto11, i2.next()); 
    assertEquals("From: Tilastot line: 269", tilasto22, i2.next()); 
    assertEquals("From: Tilastot line: 270", tilasto12, i2.next()); 
    assertEquals("From: Tilastot line: 271", tilasto23, i2.next()); 
    try {
    assertEquals("From: Tilastot line: 272", tilasto12, i2.next()); 
    fail("Tilastot: 272 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaTilastot287 */
  @Test
  public void testAnnaTilastot287() {    // Tilastot: 287
    Tilastot tilastoidut = new Tilastot(); 
    Tilasto tilasto21 = new Tilasto(2); tilastoidut.lisaa(tilasto21); 
    Tilasto tilasto11 = new Tilasto(1); tilastoidut.lisaa(tilasto11); 
    Tilasto tilasto22 = new Tilasto(2); tilastoidut.lisaa(tilasto22); 
    Tilasto tilasto12 = new Tilasto(1); tilastoidut.lisaa(tilasto12); 
    Tilasto tilasto23 = new Tilasto(2); tilastoidut.lisaa(tilasto23); 
    Tilasto tilasto51 = new Tilasto(5); tilastoidut.lisaa(tilasto51); 
    List<Tilasto> loytyneet; 
    loytyneet = tilastoidut.annaTilastot(3); 
    assertEquals("From: Tilastot line: 300", 0, loytyneet.size()); 
    loytyneet = tilastoidut.annaTilastot(1); 
    assertEquals("From: Tilastot line: 302", 2, loytyneet.size()); 
    assertEquals("From: Tilastot line: 303", true, loytyneet.get(0) == tilasto11); 
    assertEquals("From: Tilastot line: 304", true, loytyneet.get(1) == tilasto12); 
    loytyneet = tilastoidut.annaTilastot(5); 
    assertEquals("From: Tilastot line: 306", 1, loytyneet.size()); 
    assertEquals("From: Tilastot line: 307", true, loytyneet.get(0) == tilasto51); 
  } // Generated by ComTest END
}