package lentopallotilastotyokalu.test;
// Generated by ComTest BEGIN
import java.io.File;
import lentopallotilastotyokalu.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.06 09:35:43 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TilastotTest {



  // Generated by ComTest BEGIN
  /** testPoistaViimeisin49 */
  @Test
  public void testPoistaViimeisin49() {    // Tilastot: 49
    Tilastot tilastot = new Tilastot(); 
    Tilasto tilasto1 = new Tilasto(), tilasto2 = new Tilasto(), tilasto3 = new Tilasto(); 
    tilasto1.taytaEsimerkkiTiedoilla(1); tilasto2.taytaEsimerkkiTiedoilla(1); tilasto3.taytaEsimerkkiTiedoilla(1); 
    tilastot.lisaa(tilasto1); tilastot.lisaa(tilasto2); tilastot.lisaa(tilasto3); 
    assertEquals("From: Tilastot line: 54", 3, tilastot.getLkm()); 
    tilastot.poistaViimeisin(); assertEquals("From: Tilastot line: 55", 2, tilastot.getLkm()); 
    tilastot.poistaViimeisin(); assertEquals("From: Tilastot line: 56", 1, tilastot.getLkm()); 
    tilastot.poistaViimeisin(); assertEquals("From: Tilastot line: 57", 0, tilastot.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta81 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta81() throws SailoException {    // Tilastot: 81
    Tilastot tilastot = new Tilastot(); 
    Tilasto tilasto1 = new Tilasto(), tilasto2 = new Tilasto(); 
    tilasto1.taytaEsimerkkiTiedoilla(5); 
    tilasto2.taytaEsimerkkiTiedoilla(5); 
    String testiTiedosto = "testitilastot"; 
    File ftied = new File(testiTiedosto+".dat"); 
    ftied.delete(); 
    try {
    tilastot.lueTiedostosta(testiTiedosto); 
    fail("Tilastot: 92 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    tilastot.lisaa(tilasto1); 
    tilastot.lisaa(tilasto2); 
    tilastot.tallenna(); 
    tilastot = new Tilastot();  // Poistetaan vanhat luomalla uusi
    tilastot.lueTiedostosta(testiTiedosto);  // johon ladataan tiedot tiedostosta.
    Iterator<Tilasto> i = tilastot.iterator(); 
    assertEquals("From: Tilastot line: 99", tilasto1.toString(), i.next().toString()); 
    assertEquals("From: Tilastot line: 100", tilasto2.toString(), i.next().toString()); 
    assertEquals("From: Tilastot line: 101", false, i.hasNext()); 
    tilastot.lisaa(tilasto2); 
    tilastot.tallenna(); 
    assertEquals("From: Tilastot line: 104", true, ftied.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator183 */
  @Test
  public void testIterator183() {    // Tilastot: 183
    Tilastot tilastoidut = new Tilastot(); 
    Tilasto tilasto21 = new Tilasto(2); tilastoidut.lisaa(tilasto21); 
    Tilasto tilasto11 = new Tilasto(1); tilastoidut.lisaa(tilasto11); 
    Tilasto tilasto22 = new Tilasto(2); tilastoidut.lisaa(tilasto22); 
    Tilasto tilasto12 = new Tilasto(1); tilastoidut.lisaa(tilasto12); 
    Tilasto tilasto23 = new Tilasto(2); tilastoidut.lisaa(tilasto23); 
    Iterator<Tilasto> i2=tilastoidut.iterator(); 
    assertEquals("From: Tilastot line: 195", tilasto21, i2.next()); 
    assertEquals("From: Tilastot line: 196", tilasto11, i2.next()); 
    assertEquals("From: Tilastot line: 197", tilasto22, i2.next()); 
    assertEquals("From: Tilastot line: 198", tilasto12, i2.next()); 
    assertEquals("From: Tilastot line: 199", tilasto23, i2.next()); 
    try {
    assertEquals("From: Tilastot line: 200", tilasto12, i2.next()); 
    fail("Tilastot: 200 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaTilastot215 */
  @Test
  public void testAnnaTilastot215() {    // Tilastot: 215
    Tilastot tilastoidut = new Tilastot(); 
    Tilasto tilasto21 = new Tilasto(2); tilastoidut.lisaa(tilasto21); 
    Tilasto tilasto11 = new Tilasto(1); tilastoidut.lisaa(tilasto11); 
    Tilasto tilasto22 = new Tilasto(2); tilastoidut.lisaa(tilasto22); 
    Tilasto tilasto12 = new Tilasto(1); tilastoidut.lisaa(tilasto12); 
    Tilasto tilasto23 = new Tilasto(2); tilastoidut.lisaa(tilasto23); 
    Tilasto tilasto51 = new Tilasto(5); tilastoidut.lisaa(tilasto51); 
    List<Tilasto> loytyneet; 
    loytyneet = tilastoidut.annaTilastot(3); 
    assertEquals("From: Tilastot line: 228", 0, loytyneet.size()); 
    loytyneet = tilastoidut.annaTilastot(1); 
    assertEquals("From: Tilastot line: 230", 2, loytyneet.size()); 
    assertEquals("From: Tilastot line: 231", true, loytyneet.get(0) == tilasto11); 
    assertEquals("From: Tilastot line: 232", true, loytyneet.get(1) == tilasto12); 
    loytyneet = tilastoidut.annaTilastot(5); 
    assertEquals("From: Tilastot line: 234", 1, loytyneet.size()); 
    assertEquals("From: Tilastot line: 235", true, loytyneet.get(0) == tilasto51); 
  } // Generated by ComTest END
}