package lentopallotilastotyokalu.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import lentopallotilastotyokalu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.30 14:03:05 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TilastoTest {



  // Generated by ComTest BEGIN
  /** testTilasto50 */
  @Test
  public void testTilasto50() {    // Tilasto: 50
    Tilasto suorite = new Tilasto(1, "22.12.2121", "Puulaaki", "Ässä"); 
    Tilasto suorite2 = new Tilasto(3, "22.12.2121","VaLePa", "Piste"); 
    assertEquals("From: Tilasto line: 53", "1|22.12.2121|Puulaaki|0|1|0|0|0|", suorite.toString()); 
    assertEquals("From: Tilasto line: 54", "3|22.12.2121|VaLePa|0|0|0|1|0|", suorite2.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString115 */
  @Test
  public void testToString115() {    // Tilasto: 115
    Tilasto tilasto = new Tilasto(); 
    tilasto.parse("4   |26.1.2021    |Karvapallot   |1     |0      |0     |0      |0      |"); 
    assertEquals("From: Tilasto line: 118", "4|26.1.2021|Karvapallot|1|0|0|0|0|", tilasto.toString()); 
  } // Generated by ComTest END
}